name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello.py
      run: python Hello.py
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
